term=foot

font=Mononoki Nerd Font Mono:size=14
pad=10x20x10x0

[bell]
system=no

[scrollback]
lines=10000

[cursor]
style=beam

[colors-dark]
alpha=0.8
blur=yes
foreground=DEEEED
background=0A0A0A

cursor=0A0A0A DEEEED 
# Regular colors
regular0=080808  # black
regular1=663333  # red
regular2=789978  # green
regular3=dfAA88  # yellow
regular4=7788AA  # blue
regular5=a780aD  # magenta
regular6=708090  # cyan
regular7=DEEEED  # white

# Bright colors
bright0=444444  # black
bright1=663333  # red
bright2=789978  # green
bright3=dfAA88  # yellow
bright4=7788AA  # blue
bright5=a780aD  # magenta
bright6=708090  # cyan
bright7=DEEEED  # white

# Selection colors
selection-foreground=DEEEED
selection-background=7A7A7A

# URL underline color
urls=D7007D

[key-bindings]
font-reset=none

# vim: ft=dosini
