[colors]
bg =      "1F1F28"
fg =      "dcd7ba"
bg_light = "2A2A37"
blue_dark = "223249"
grey = "727169"
yellow = "C8C093"
violet = "938AA9"
violet_dark = "363646"
black =      "1F1F28"
red =        "C34043"
orange = "FFA066"
orange_light = "DCA561"
green =      "98BB6C"
blue =       "7EB3C9"
blue_light = "7FB4CA"
magenta =    "957FB8"
cyan =       "7EB3C9"
white =      "DDD8BB"
red_light =       "D27E99"
green_light =     "9EC967"
yellow_light =    "F1C982"
magenta_light =   "A98FD2"
cyan_light =      "7BC2DF"
white_light =     "A8A48D"

[base16]
scheme = "My"
author = "Me"
base00 = "bg"
base01 = "bg_light"
base02 = "blue_dark"
base03 = "grey"
base04 = "yellow"
base05 = "fg"
base06 = "violet"
base07 = "violet_dark"
base08 = "red_light"
base09 = "orange"
base0A = "orange_light"
base0B = "green"
base0C = "blue_light"
base0D = "cyan"
base0E = "magenta"
base0F = "red_light"
