[colorgen]
name = 'test'
reload = true
dir = '~/.config/colors/'

[config.nvim16]
path = 'base16.lua'
before = 'return {'
format = "  {name} = '#{value}',"
after = '}'
base16 = true

[config.nvim]
path = 'colors.lua'
before = 'return {'
format = "  {name} = '#{value}',"
after = '}'

[config.css]
path = 'colors.css'
format = '@define-color {name} #{value};'

[config.sketchybar]
path = 'sketchybar.sh'
format = '{name}=\"{value}\"'
reload = 'sketchybar --reload'

[config.tmux]
path = '.tmux.conf.colors'
format = 'set -g @{name} "#{value}"'
reload = 'tmux source-file ~/.tmux.conf'

[config.wezterm]
path = 'wezterm.yaml'
format = '{name}: {value}'
base16 = true
meta = true
reload = 'shortcuts run reloadwez'
