[colors]
bg =            "272e33" #"#272e33"
bg_light =      "414b50" #"#414b50"
fg =            "d3c6aa" #"#d3c6aa"
black =         "191D24" #"#191D24"
red =           "e67e80" #"#e67e80"
orange =        "e69875" #"#e69875"
yellow =        "dbbc7f" #"#dbbc7f"
green =         "a7c080" #"#a7c080"
aqua =          "83c092" #"#83c092"
cyan =          "83c092" #"#83c092"
blue =          "7fbbb3" #"#7fbbb3"
purple =        "d699b6" #"#d699b6"
magenta =       "d699b6" #"#d699b6"
grey =          "7a8478" #"#7a8478"
grey1 =         "859289" #"#859289"
grey2 =         "9da9a0" #"#9da9a0"

[base16]
scheme = "My"
author = "Me"
base00 = "bg"
base01 = "bg_light"
base02 = "grey2"
base03 = "bg_light"
base04 = "grey"
base05 = "fg"
base06 = "fg"
base07 = "fg"
base08 = "red"
base09 = "magenta"
base0A = "yellow"
base0B = "green"
base0C = "aqua"
base0D = "blue"
base0E = "magenta"
base0F = "magenta"
