[colors]
bg              = "282828" ##282828
bg_light        = "32302f" ##32302f
grey            = "928374" ##928374
fg              = "fbf1c7" ##fbf1c7
red             = "fb4934" ##fb4934
green           = "b8bb26" ##b8bb26
yellow          = "fabd2f" ##fabd2f
blue            = "83a598" ##83a598
purple          = "d3869b" ##d3869b
magenta         = "d3869b" ##d3869b
cyan            = "8ec07c" ##8ec07c
orange          = "fe8019" ##fe8019

[base16]
scheme = "My"
author = "Me"
base00 = "bg"
base01 = "bg_light"
base02 = "grey"
base03 = "grey"
base04 = "fg"
base05 = "fg"
base06 = "fg"
base07 = "fg"
base08 = "blue"
base09 = "purple"
base0A = "green"
base0B = "yellow"
base0C = "orange"
base0D = "cyan"
base0E = "red"
base0F = "purple"
