[colors]
bg =            "1F1F28"#"#1F1F28"
bg_light =      "2A2A37"#"#2A2A37"
fg =            "dcd7ba"#"#dcd7ba"
grey =          "727169"#"#727169"
black =         "1F1F28"#"#1F1F28"
yellow =        "C8C093"#"#C8C093"
yellow_light =  "F1C982"#"#F1C982"
violet =        "938AA9"#"#938AA9"
violet_dark =   "363646"#"#363646"
red =           "C34043"#"#C34043"
red_light =     "D27E99"#"#D27E99"
orange =        "FFA066"#"#FFA066"
orange_light =  "DCA561"#"#DCA561"
green =         "98BB6C"#"#98BB6C"
green_light =   "9EC967"#"#9EC967"
blue =          "7EB3C9"#"#7EB3C9"
blue_light =    "7FB4CA"#"#7FB4CA"
blue_dark =     "223249"#"#223249"
magenta =       "957FB8"#"#957FB8"
magenta_light = "A98FD2"#"#A98FD2"
cyan =          "7EB3C9"#"#7EB3C9"
cyan_light =    "7BC2DF"#"#7BC2DF"
white =         "DDD8BB"#"#DDD8BB"
white_light =   "A8A48D"#"#A8A48D"

[base16]
scheme = "My"
author = "Me"
base00 = "bg"
base01 = "bg_light"
base02 = "blue_dark"
base03 = "grey"
base04 = "yellow"
base05 = "fg"
base06 = "violet"
base07 = "violet_dark"
base08 = "red_light"
base09 = "orange"
base0A = "orange_light"
base0B = "green"
base0C = "blue_light"
base0D = "cyan"
base0E = "magenta"
base0F = "red_light"
