[colors]
black =         "191D24" ##191D24
black1 =        "1E222A" ##1E222A
bg_light =      "222630" ##222630
bg =            "242933" ##242933

grey =          "2E3440" ##2E3440
grey2 =         "3B4252" ##3B4252
grey3 =         "434C5E" ##434C5E
grey4 =         "4C566A" ##4C566A
grey5 =         "60728A" ##60728A
fg =            "BBC3D4" ##BBC3D4

white =         "C0C8D8" ##C0C8D8
white1 =        "D8DEE9" ##D8DEE9
white2 =        "E5E9F0" ##E5E9F0
white3 =        "ECEFF4" ##ECEFF4
                         #       
blue =          "5E81AC" ##5E81AC
blue1 =         "81A1C1" ##81A1C1
blue2 =         "88C0D0" ##88C0D0
                         #       
cyan =          "8FBCBB" ##8FBCBB
cyan_bright =   "9FC6C5" ##9FC6C5
cyan_dim =      "80B3B2" ##80B3B2

red =           "BF616A" ##BF616A
red_bright =    "C5727A" ##C5727A
red_dim =       "B74E58" ##B74E58

orange =        "D08770" ##D08770
orange_bright = "D79784" ##D79784
orange_dim =    "CB775D" ##CB775D

yellow =        "EBCB8B" ##EBCB8B
yellow_bright = "EFD49F" ##EFD49F
yellow_dim =    "E7C173" ##E7C173

green =         "A3BE8C" ##A3BE8C
green_bright =  "B1C89D" ##B1C89D
green_dim =     "97B67C" ##97B67C

magenta =       "B48EAD" ##B48EAD
magenta_bright ="BE9DB8" ##BE9DB8
magenta_dim =   "A97EA1" ##A97EA1

[base16]
scheme = "My"
author = "Me"
base00 = "bg"
base01 = "bg_light"
base02 = "grey2"
base03 = "grey3"
base04 = "fg"
base05 = "white3"
base06 = "white1"
base07 = "white2"
base08 = "red_bright"
base09 = "magenta"
base0A = "yellow_bright"
base0B = "green_bright"
base0C = "cyan"
base0D = "blue2"
base0E = "magenta"
base0F = "magenta"
